'''
'''

from ..utils import _import

_import(locals())

# Params
PARAMS_SHUFFLE = 'wAEB8gECGAE%3D'
PARAMS_RADIO   = 'wAEB'

# Search Parameter Prefixes
SEARCH_PARAM_PREFIX    = 'Eg-KAQwIA'
# SEARCH_PARAM_SUFFIX    = 'MABqChAEEAMQCRAFEAo%3D'
SEARCH_PARAM_SUFFIX    = 'MABqChADEAQQCRAKEAU%3D'
SEARCH_PARAM_ALBUMS    = 'BAAGAEgACgA'
SEARCH_PARAM_PLAYLISTS = 'BAAGAAgACgB'
SEARCH_PARAM_VIDEOS    = 'BABGAAgACgA'
SEARCH_PARAM_ARTISTS   = 'BAAGAAgASgA'
SEARCH_PARAM_SONGS     = 'RAAGAAgACgA'
